# Mail
spring.mail.password=YOUR_GMAIL_APP_PASSWORD

# JWT
jwt.secret=YOUR_JWT_SECRET

# Google OAuth2
google.client.id=YOUR_GOOGLE_CLIENT_ID
google.client.secret=YOUR_GOOGLE_CLIENT_SECRET

# Groq
groq.api.key=YOUR_GROQ_API_KEY