spring.security.oauth2.client.registration.google.client-id=817149806524-jiv0gm6tnei33lvi5be84p66t31m92dh.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

groq.api.key=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
spring.mail.password=hqqwvfmitysfnycm