spring.application.name=ami-backend

spring.config.import=optional:classpath:application-secret.properties

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/ami
spring.datasource.username=root
spring.datasource.password=Aditya@30

# Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=2004adityakute@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.expiration=86400000

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${google.client.id}
spring.security.oauth2.client.registration.google.client-secret=${google.client.secret}
spring.security.oauth2.client.registration.google.scope=email,profile

# Groq
groq.model=llama-3.3-70b-versatile

locationiq.api-key=pk.5fee178b21647f953f82d9bc6994075f


# Razorpay
razorpay.key-id=${razorpay.key.id}
razorpay.key-secret=${razorpay.key.secret}
razorpay.currency=INR

