spring.application.name=ami-backend

spring.config.import=optional:classpath:application-secret.properties

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/ami_db
spring.datasource.username=root
spring.datasource.password=Vishal@966

# Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=2004adityakute@gmail.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

groq.model=llama-3.3-70b-versatile